#!/bin/bash

set -euo pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
ROOTDIR=$(realpath $SCRIPTDIR/..)

# sed behaves differently on different platforms
# sed --version is not valid on BSD, while it is valid on the GNU version
SED_CMD() {
    if sed --version > /dev/null 2>&1; then
        # GNU version
        sed -i "$@"
    else
        # BSD version
        sed -i "" "$@"
    fi
}

# get gitops templates
REPO='https://github.com/redhat-appstudio/tssc-sample-gitops'
REPONAME=$(basename $REPO)

TEMPDIR=$ROOTDIR/temp
rm -rf $TEMPDIR # clean up
mkdir -p $TEMPDIR
cd $TEMPDIR
git clone $REPO 2>&1 > /dev/null


DEST=$ROOTDIR/skeleton/gitops-template
rm -rf $DEST/components
rm -rf $DEST/app-of-apps
rm -rf $DEST/application.yaml
mkdir -p $DEST/components
mkdir -p $DEST/app-of-apps
cp -r $TEMPDIR/$REPONAME/templates/app-of-apps $DEST/
cp -r $TEMPDIR/$REPONAME/templates/http $DEST/components/http     # only support http now
cp -r $TEMPDIR/$REPONAME/templates/application.yaml $DEST/
rm -rf $TEMPDIR

# replace {{value}} to ${{ value }} for software templates
SED_CMD "s/{{/\${{ /g" $DEST/application.yaml
SED_CMD "s/}}/ }}/g" $DEST/application.yaml

function iterate() {
  local dir="$1"

  for file in "$dir"/*; do
    if [ -f "$file" ]; then
      SED_CMD "s/{{/\${{ /g" $file
      SED_CMD "s/}}/ }}/g" $file
    fi

    if [ -d "$file" ]; then
      iterate "$file"
    fi
  done
}

iterate $DEST/components
iterate $DEST/app-of-apps

